# config.yaml (add-on)
name: "Surikat Homeassistant"
description: "Surikat plugin for Homeassistant"
version: "0.1"
slug: "surikat-ha"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
options:
  gateway_user: "user"
  gateway_password: "password"
  mqtt_host: "mqtt://localhost"
  mqtt_port: 1883
  mqtt_topic: "frigate/events"
  mqtt_user: "user"
  mqtt_password: "password"
  enable_logs: false
schema:
  gateway_user: str
  gateway_password: str
  mqtt_host: str
  mqtt_port: port
  mqtt_topic: str
  mqtt_user: str
  mqtt_password: str
  enable_logs: bool
map:
  config:
    target: /config
    readonly: false