# config.yaml (add-on)
name: "Surikat Homeassistant"
description: "Surikat plugin for Homeassistant"
version: "1.0.21"
slug: "surikat-ha"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
options:
  mqtt_host: "mqtt://localhost"
  mqtt_port: 1883
  mqtt_topic: "frigate/events"
  mqtt_user: "user"
  mqtt_password: "password"
  default_name: "password"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_topic: str
  mqtt_user: str
  mqtt_password: str
  default_name: str
map:
  config:
    target: /config
    readonly: false