name: Surikat HA
slug: surikat-ha
version: "0.1.0"
description: Edit YAML configs securely
startup: services
boot: auto
host_network: true

options:
  port: 8129

schema:
  port: int

map:
  - config:rw

ports:
  8129/tcp: 8129

ingress: false
