# config.yaml

# Fichier central qui définit la configuration de l’add-on.
# Contient des informations comme :
# Nom, version, description
# Configuration requise (ports, volumes, options)
# Dépendances

# Images Docker à utiliser
# C’est ce fichier que Home Assistant lit pour comprendre comment installer et lancer ton add-on.

name: "Surikat HA"
description: "My first real add-on!"
url: "https://github.com/surikat-ch/surikat-ha-repo"
version: "1.0.8"
slug: "surikat_ha"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  123/tcp: 123
map:
  - type: share
    read_only: False
  - type: ssl
  - type: homeassistant_config
    read_only: False
    path: /custom/config/path
image: repo/{arch}-surikat-ha